language: go

go:
  - 1.10.x
  - master
os:
  - linux

git:
  depth: 1

install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - go get ./...

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled