language: go

go:
  - 1.10.x
  - master
os:
  - linux

git:
  depth: 1

install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - go get ./...

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success https://discordapp.com/api/webhooks/486498539183013919/RojI1EXfpN75FcuXXVVhWqwl49mbKDZS_VLrOe4nOFoubI569jLuCx6GT4u2yGyEQU2W
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure https://discordapp.com/api/webhooks/486498539183013919/RojI1EXfpN75FcuXXVVhWqwl49mbKDZS_VLrOe4nOFoubI569jLuCx6GT4u2yGyEQU2W